name: Trigger update of core-curriculum/web

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Trigger update of core-curriculum/web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - name: Dispatch workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_and_deploy.yml
          repo: core-curriculum/web  
          token: ${{ steps.app-token.outputs.token }} 
